# To activate this file, begin the application with the system property -Dspring.profiles.active=local.
# Alternatively, utilize the environment property SPRING_PROFILES_ACTIVE=local.
# If the local profile is active and a property is present in both YAML files, the one specified here will override the other.
# Any property not present here will default to the application.yml file if utilized by the application.
server:
  port: 8088

# ----------------- spring related configuration starts ----------------------------
spring:
  config:
    activate:
      on-profile: local


  docker:
    compose:
      # other values are none, start-only,
      lifecycle-management: start_and_stop


  jpa:
    # default is false
    generate-ddl: false
    hibernate:
      # default is none
      ddl-auto: none
    # default is false
    show-sql: false
    # default is false
    defer-datasource-initialization: false
    datasource:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      hikari:
        # default is 30000, 30 secs
        connectionTimeout: 20000
        #default is 10
        maximumPoolSize: 5

  sql:
    init:
      # default is always for in-memory db. Other value is embedded, never. Causes auto execution of db scripts.
      # To be used only for local dev.
      mode: never

# ----------------- spring related configuration ends ----------------------------