server:
  port: 8088

spring:
  application:
    spring.datasource.username: phlat
    spring.datasource.password: password
    
    logging.level.root: INFO
    # logging.level.root=TRACE
    # logging.level.root=DEBUG
    # logging.level.root=ERROR

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://common-logon-test.hlth.gov.bc.ca/auth/realms/moh_applications
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: PHLAT
      principle-attribute: preferred_username

