# to activate this file start the application with system property -Dspring.profiles.active=local
# or use env property SPRING_PROFILES_ACTIVE=local
server:
  port: 8088

# ----------------- spring related configuration starts ----------------------------
spring:
  config:
    activate:
      on-profile: local


  docker:
    compose:
      # other values are none, start-only,
      lifecycle-management: start_and_stop



  jpa:
    # default is false
    generate-ddl: false
    hibernate:
      # default is none
      ddl-auto: none
    # default is false
    show-sql: false
    # default is false
    defer-datasource-initialization: false
    datasource:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      hikari:
        # default is 30000, 30 secs
        connectionTimeout: 20000
        #default is 10
        maximumPoolSize: 5

  sql:
    init:
      # default is always for in-memory db. Other value is embedded. Causes auto execution of db scripts.
      # To be used only for local dev.
      mode: never

  servlet:
    multipart:
      # total request size limit
      max-request-size: 25MB
      # upload file size limit
      max-file-size: 24MB
      # above this size, tomcat will save it to temp dir.
      file-size-threshold: 22MB
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://common-logon-test.hlth.gov.bc.ca/auth/realms/moh_applications
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

# ----------------- spring related configuration ends ----------------------------


jwt:
  auth:
    converter:
      resource-id: PHLAT-WEB
      principle-attribute: preferred_username
