server:
  port: 8088

spring:
  application:
    spring.datasource.username: phlat
    spring.datasource.password: password
    
    logging.level.root: INFO
    # logging.level.root=TRACE
    # logging.level.root=DEBUG
    # logging.level.root=ERROR

