# this is default profile that is active for all environments.
server:
  port: 8088

# -------------- spring related config starts ---------------------------

spring:

  jpa:
    # default is false
    generate-ddl: false
    hibernate:
      # default is none
      ddl-auto: none
    # default is false
    show-sql: false
    # default is false
    defer-datasource-initialization: false

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      # default is 30000, 30 secs
      connectionTimeout: 20000
      #default is 10
      maximumPoolSize: 5

  sql:
    init:
      # default is always for in-memory db. Other value is embedded. Causes auto execution of db scripts.
      # To be used only for local dev.
      mode: never

  servlet:
    multipart:
      # total request size limit
      max-request-size: 25MB
      # upload file size limit
      max-file-size: 24MB
      # above this size, tomcat will save it to temp dir.
      file-size-threshold: 25MB
      enabled: true

  flyway:
    locations: classpath:db/migration
    enabled: true


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_PROVIDER_URL}
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  ssl:
    bundle:
      pem:
        client:
          truststore:
            certificate: classpath:plr_tls_trust.cert

# -------------- spring related config ends ---------------------------

jwt:
  auth:
    converter:
      resource-id: ${KEYCLOAK_CLIENT_ID_WEB}
      principle-attribute: preferred_username



# application specific configuration
columns-display-preference:
  allowed-viewNames: file-task-management,process-data-management,source-data-management,status-codes-management

plr:
  boundary:
    host: ${PLR_API_HOST}
    org-id: 00002855
    role: REG_ADMIN

    keycloak:
      provider-url: ${PLR_KEYCLOAK_PROVIDER_URL}
      client-id: ${PLR_KEYCLOAK_CLIENT_ID}
      client-secret: ${PLR_KEYCLOAK_CLIENT_SECRET}

resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
  retry:
    retryAspectOrder: 2

resilience4j.circuitbreaker:
  instances:
    callPlrCircuitBreaker:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 3
      minimumNumberOfCalls: 3
      failureRateThreshold: 100
      waitDurationInOpenState: 60000
      permittedNumberOfCallsInHalfOpenState: 2

resilience4j.retry:
  instances:
    callPlrRetry:
      maxAttempts: 3
      waitDuration: 1000
      retryExceptions:
      - org.springframework.web.reactive.function.client.WebClientResponseException
