-- this file is include only if you need to prepoulate the tables
INSERT INTO roles(code, description)  VALUES ('REG_USER','Regisry User');
INSERT INTO roles(code, description)  VALUES ('REG_ADMIN','Regisry Administrative User');

INSERT INTO users(user_id, first_name, last_name) values('LYSONLE','Ly-Son','Le');
INSERT INTO users(user_id, first_name, last_name) values('PTUGGER','Prhabhjot','Tugger');
INSERT INTO users(user_id, first_name, last_name) values('SALSYED','Salman','Syed');
INSERT INTO users(user_id, first_name, last_name) values('JOBURTON','Josual','Burton');
INSERT INTO users(user_id, first_name, last_name) values('LWOO','Linda','Woo');
INSERT INTO users(user_id, first_name, last_name) values('LBAIGENT','Lindsay','Baigent');

INSERT INTO USER_ROLE(USER_ID, ROLE_CODE)  VALUES ('LYSONLE','REG_ADMIN');

INSERT INTO STATUS(CODE,DESCRIPTION) VALUES 
('INITIAL','SET STATUS FOR ALL RECORDS WHEN THE RECORD IS INITIALLY LOADED INTO THE PHAT TABLE.');

INSERT INTO  STATUS(CODE,DESCRIPTION) VALUES 
('PHYS_ADDR MANDATORY','SET STATUS IF PHYS_ADDR1 OR PHYS_ADDR_CITY IS MISSING.');

INSERT INTO  STATUS(CODE,DESCRIPTION) VALUES 
('HDS_NAME_MANDATORY','SET STATUS IF HDS_NAME IS MISSING.');
	
INSERT INTO  STATUS(CODE,DESCRIPTION) VALUES 
('AD_PHYS_ADDR_INVALID','SET STATUS IF PHYS_ADDR_MAILABILITY_SCORE < 3.');

INSERT INTO  STATUS(CODE,DESCRIPTION) VALUES 
('AD_MAIL_ADDR_INVALID','SET STATUS IF MAIL_ADDR_MAILABILITY_SCORE < 3.');

INSERT INTO  STATUS(CODE,DESCRIPTION) VALUES 
('DATABC_CIVIC_ADDR_INVALID','SET STATUS IF DATABC_SCORE < 96 OR DATABC_PRECISION_POINT < 99.');

INSERT INTO  STATUS(CODE,DESCRIPTION) VALUES 
('OOP_ADDRESS','SET STATUS IF AD_PHYS_ADDR_PROVINCE_CODE <> ‘BC’ OR  AD_PHYS_ADDR_COUNTRY <> ‘CA’.');

INSERT INTO  STATUS(CODE,DESCRIPTION) VALUES 
('DUPLICATE_HIGH_CONF_INTERNAL','SET STATUS IF ???');

INSERT INTO  STATUS(CODE,DESCRIPTION) VALUES 
('DO_NOT_LOAD','SET STATUS IF DO NOT LOAD FLAG IS SET TO ‘Y’.');

INSERT INTO  STATUS(CODE,DESCRIPTION) VALUES 
('HDS_NON_SURVIVOR','SET STATUS IF INTERNAL_ID <> HDS_SURV_INTERNAL_ID.');

INSERT INTO  STATUS(CODE,DESCRIPTION) VALUES 
('FACILITY_NON_SURVIVOR','SET STATUS IF INTERNAL_ID <> FACILITY_SURV_INTERNAL_ID.');

INSERT INTO  STATUS(CODE,DESCRIPTION) VALUES 
('VALID','SET STATUS IF RECORD HAS BEEN VALIDATED AND RECORD IS READY TO LOAD INTO THE PLR.');

INSERT INTO  STATUS(CODE,DESCRIPTION) VALUES 
('COMPLETE','SET STATUS IF RECORD HAS BEEN SUCCESSFULLY LOADED INTO THE PLR.');

INSERT INTO  STATUS(CODE,DESCRIPTION) VALUES 
('LOAD_ERROR','SET STATUS IF RECORD LOAD INTO THE PLR WAS UNSUCCESSFUL.');

INSERT INTO  STATUS(CODE,DESCRIPTION) VALUES 
('APPROVED','SET STATUS IF RECORD IS APPROVED TO BE LOADED INTO THE PLR.');

INSERT INTO  STATUS(CODE,DESCRIPTION) VALUES 
('UPLOAD_IN_PROGRESS','UPLOAD IN PROGRESS.');

INSERT INTO  STATUS(CODE,DESCRIPTION) VALUES 
('UPLOAD_COMPLETED','UPLOAD COMPLETED.');

-- seeded data for table and column info
-- this table stores the column header name used for uploading and the variable names used for UI Hide and Show feature

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'DO_NOT_LOAD', 'DO_NOT_LOAD', 'doNotLoad'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'STACKHOLDER', 'STACKHOLDER', 'stackholder'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_IPC_ID', 'HDS_IPC_ID', 'hdsIpcId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_CPN_ID', 'HDS_CPN_ID', 'hdsCpnId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_PROVIDER_IDENTIFIER1', 'HDS_PROVIDER_IDENTIFIER1', 'hdsProviderIdentifier1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_PROVIDER_IDENTIFIER2', 'HDS_PROVIDER_IDENTIFIER2', 'hdsProviderIdentifier2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_PROVIDER_IDENTIFIER3', 'HDS_PROVIDER_IDENTIFIER3', 'hdsProviderIdentifier3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_PROVIDER_IDENTIFIER_TYPE1', 'HDS_PROVIDER_IDENTIFIER_TYPE1', 'hdsProviderIdentifierType1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_PROVIDER_IDENTIFIER_TYPE2', 'HDS_PROVIDER_IDENTIFIER_TYPE2', 'hdsProviderIdentifierType2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_PROVIDER_IDENTIFIER_TYPE3', 'HDS_PROVIDER_IDENTIFIER_TYPE3', 'hdsProviderIdentifierType3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_HIBC_FACILITY_ID', 'HDS_HIBC_FACILITY_ID', 'hdsHibcFacilityId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_TYPE', 'HDS_TYPE', 'hdsType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_NAME', 'HDS_NAME', 'hdsName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_NAME_ALIAS', 'HDS_NAME_ALIAS', 'hdsNameAlias'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_PREFERRED_NAME_FLAG', 'HDS_PREFERRED_NAME_FLAG', 'hdsPreferredNameFlag'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_EMAIL', 'HDS_EMAIL', 'hdsEmail'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_WEBSITE', 'HDS_WEBSITE', 'hdsWebsite'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_BUS_TEL_AREA_CODE', 'HDS_BUS_TEL_AREA_CODE', 'hdsBusTelAreaCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_BUS_TEL_NUMBER', 'HDS_BUS_TEL_NUMBER', 'hdsBusTelNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_TEL_EXTENSION', 'HDS_TEL_EXTENSION', 'hdsTelExtension'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_CELL_AREA_CODE', 'HDS_CELL_AREA_CODE', 'hdsCellAreaCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_CELL_NUMBER', 'HDS_CELL_NUMBER', 'hdsCellNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_FAX_AREA_CODE', 'HDS_FAX_AREA_CODE', 'hdsFaxAreaCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_FAX_NUMBER', 'HDS_FAX_NUMBER', 'hdsFaxNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_SERVICE_DELIVERY_TYPE', 'HDS_SERVICE_DELIVERY_TYPE', 'hdsServiceDeliveryType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PCN_CLINIC_TYPE', 'PCN_CLINIC_TYPE', 'pcnClinicType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PCN_PCI_FLAG', 'PCN_PCI_FLAG', 'pcnPciFlag'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_HOURS_OF_OPERATION', 'HDS_HOURS_OF_OPERATION', 'hdsHoursOfOperation'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_CONTACT_NAME', 'HDS_CONTACT_NAME', 'hdsContactName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_IS_FOR_PROFIT_FLAG', 'HDS_IS_FOR_PROFIT_FLAG', 'hdsIsForProfitFlag'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'SOURCE_STATUS', 'SOURCE_STATUS', 'sourceStatus'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_PARENT_IPC_ID', 'HDS_PARENT_IPC_ID', 'hdsParentIpcId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'BUS_IPC_ID', 'BUS_IPC_ID', 'busIpcId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'BUS_CPN_ID', 'BUS_CPN_ID', 'busCpnId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'BUS_NAME', 'BUS_NAME', 'busName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'BUS_LEGAL_NAME', 'BUS_LEGAL_NAME', 'busLegalName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'BUS_PAYEE_NUMBER', 'BUS_PAYEE_NUMBER', 'busPayeeNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'BUS_OWNER_NAME', 'BUS_OWNER_NAME', 'busOwnerName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'BUS_OWNER_TYPE', 'BUS_OWNER_TYPE', 'busOwnerType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'BUS_OWNER_TYPE_OTHER', 'BUS_OWNER_TYPE_OTHER', 'busOwnerTypeOther'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'FAC_BUILDING_NAME', 'FAC_BUILDING_NAME', 'facBuildingName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'FACILITY_HDS_DETAILS_ADDITIONAL_INFO', 'FACILITY_HDS_DETAILS_ADDITIONAL_INFO', 'facilityHdsDetailsAdditionalInfo'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_ADDR1', 'PHYSICAL_ADDR1', 'physicalAddr1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_ADDR2', 'PHYSICAL_ADDR2', 'physicalAddr2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_ADDR3', 'PHYSICAL_ADDR3', 'physicalAddr3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_ADDR4', 'PHYSICAL_ADDR4', 'physicalAddr4'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_CITY', 'PHYSICAL_CITY', 'physicalCity'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_PROVINCE', 'PHYSICAL_PROVINCE', 'physicalProvince'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_PCODE', 'PHYSICAL_PCODE', 'physicalPcode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_COUNTRY', 'PHYSICAL_COUNTRY', 'physicalCountry'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYS_ADDR_IS_PRIVATE', 'PHYS_ADDR_IS_PRIVATE', 'physAddrIsPrivate'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_ADDR1', 'MAIL_ADDR1', 'mailAddr1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_ADDR2', 'MAIL_ADDR2', 'mailAddr2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_ADDR3', 'MAIL_ADDR3', 'mailAddr3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_ADDR4', 'MAIL_ADDR4', 'mailAddr4'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_CITY', 'MAIL_CITY', 'mailCity'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_BC', 'MAIL_BC', 'mailBc'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_PCODE', 'MAIL_PCODE', 'mailPcode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_COUNTRY', 'MAIL_COUNTRY', 'mailCountry'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_ADDR_IS_PRIVATE', 'MAIL_ADDR_IS_PRIVATE', 'mailAddrIsPrivate'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'ID', '', 'id'
);


-- process data table
insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'ID', 'ID', 'id'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'CONTROL_ID', 'CONTROL_ID', 'controlId'
);


insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'DO_NOT_LOAD', 'DO_NOT_LOAD', 'doNotLoad'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'STACKHOLDER', 'STACKHOLDER', 'stackholder'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_IPC_ID', 'HDS_IPC_ID', 'hdsIpcId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_CPN_ID', 'HDS_CPN_ID', 'hdsCpnId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER1', 'HDS_PROVIDER_IDENTIFIER1', 'hdsProviderIdentifier1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER2', 'HDS_PROVIDER_IDENTIFIER2', 'hdsProviderIdentifier2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER3', 'HDS_PROVIDER_IDENTIFIER3', 'hdsProviderIdentifier3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER_TYPE1', 'HDS_PROVIDER_IDENTIFIER_TYPE1', 'hdsProviderIdentifierType1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER_TYPE2', 'HDS_PROVIDER_IDENTIFIER_TYPE2', 'hdsProviderIdentifierType2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER_TYPE3', 'HDS_PROVIDER_IDENTIFIER_TYPE3', 'hdsProviderIdentifierType3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_HIBC_FACILITY_ID', 'HDS_HIBC_FACILITY_ID', 'hdsHibcFacilityId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_TYPE', 'HDS_TYPE', 'hdsType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_NAME', 'HDS_NAME', 'hdsName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_NAME_ALIAS', 'HDS_NAME_ALIAS', 'hdsNameAlias'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PREFERRED_NAME_FLAG', 'HDS_PREFERRED_NAME_FLAG', 'hdsPreferredNameFlag'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_EMAIL', 'HDS_EMAIL', 'hdsEmail'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_WEBSITE', 'HDS_WEBSITE', 'hdsWebsite'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_BUS_TEL_AREA_CODE', 'HDS_BUS_TEL_AREA_CODE', 'hdsBusTelAreaCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_BUS_TEL_NUMBER', 'HDS_BUS_TEL_NUMBER', 'hdsBusTelNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_TEL_EXTENSION', 'HDS_TEL_EXTENSION', 'hdsTelExtension'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_CELL_AREA_CODE', 'HDS_CELL_AREA_CODE', 'hdsCellAreaCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_CELL_NUMBER', 'HDS_CELL_NUMBER', 'hdsCellNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_FAX_AREA_CODE', 'HDS_FAX_AREA_CODE', 'hdsFaxAreaCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_FAX_NUMBER', 'HDS_FAX_NUMBER', 'hdsFaxNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_SERVICE_DELIVERY_TYPE', 'HDS_SERVICE_DELIVERY_TYPE', 'hdsServiceDeliveryType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PCN_CLINIC_TYPE', 'PCN_CLINIC_TYPE', 'pcnClinicType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PCN_PCI_FLAG', 'PCN_PCI_FLAG', 'pcnPciFlag'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_HOURS_OF_OPERATION', 'HDS_HOURS_OF_OPERATION', 'hdsHoursOfOperation'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_CONTACT_NAME', 'HDS_CONTACT_NAME', 'hdsContactName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_IS_FOR_PROFIT_FLAG', 'HDS_IS_FOR_PROFIT_FLAG', 'hdsIsForProfitFlag'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'SOURCE_STATUS', 'SOURCE_STATUS', 'sourceStatus'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PARENT_IPC_ID', 'HDS_PARENT_IPC_ID', 'hdsParentIpcId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'BUS_IPC_ID', 'BUS_IPC_ID', 'busIpcId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'BUS_CPN_ID', 'BUS_CPN_ID', 'busCpnId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'BUS_NAME', 'BUS_NAME', 'busName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'BUS_LEGAL_NAME', 'BUS_LEGAL_NAME', 'busLegalName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'BUS_PAYEE_NUMBER', 'BUS_PAYEE_NUMBER', 'busPayeeNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'BUS_OWNER_NAME', 'BUS_OWNER_NAME', 'busOwnerName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'BUS_OWNER_TYPE', 'BUS_OWNER_TYPE', 'busOwnerType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'BUS_OWNER_TYPE_OTHER', 'BUS_OWNER_TYPE_OTHER', 'busOwnerTypeOther'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_BUILDING_NAME', 'FAC_BUILDING_NAME', 'facBuildingName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FACILITY_HDS_DETAILS_ADDITIONAL_INFO', 'FACILITY_HDS_DETAILS_ADDITIONAL_INFO', 'facilityHdsDetailsAdditionalInfo'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_ADDR1', 'PHYSICAL_ADDR1', 'physicalAddr1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_ADDR2', 'PHYSICAL_ADDR2', 'physicalAddr2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_ADDR3', 'PHYSICAL_ADDR3', 'physicalAddr3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_ADDR4', 'PHYSICAL_ADDR4', 'physicalAddr4'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_CITY', 'PHYSICAL_CITY', 'physicalCity'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_PROVINCE', 'PHYSICAL_PROVINCE', 'physicalProvince'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_PCODE', 'PHYSICAL_PCODE', 'physicalPcode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_COUNTRY', 'PHYSICAL_COUNTRY', 'physicalCountry'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYS_ADDR_IS_PRIVATE', 'PHYS_ADDR_IS_PRIVATE', 'physAddrIsPrivate'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_ADDR1', 'MAIL_ADDR1', 'mailAddr1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_ADDR2', 'MAIL_ADDR2', 'mailAddr2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_ADDR3', 'MAIL_ADDR3', 'mailAddr3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_ADDR4', 'MAIL_ADDR4', 'mailAddr4'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_CITY', 'MAIL_CITY', 'mailCity'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_BC', 'MAIL_BC', 'mailBc'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_PCODE', 'MAIL_PCODE', 'mailPcode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_COUNTRY', 'MAIL_COUNTRY', 'mailCountry'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_ADDR_IS_PRIVATE', 'MAIL_ADDR_IS_PRIVATE', 'mailAddrIsPrivate'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'ROWSTATUS_CODE', 'ROWSTATUS_CODE', 'rowstatusCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'ERROR_MSG', 'ERROR_MSG', 'errorMsg'
);

-- ORIGINAL TRUSTED FILE FORMAT
insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'ID', '', 'id'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DO_NOT_LOAD', 'DO_NOT_LOAD', 'doNotLoad'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'INTERNAL_ID', 'INTERNAL_ID', 'internalId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'HDS_SURV_INTERNAL_ID', 'HDS_SURV_INTERNAL_ID', 'hdsSurvInternalId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'FACILITY_SURV_INTERNAL_ID', 'FACILITY_SURV_INTERNAL_ID', 'facilitySurvInternalId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'HDS_SOURCE', 'HDS_SOURCE', 'hdsSource'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'HDS_TYPE_CONCAT', 'HDS_TYPE_CONCAT', 'hdsTypeConcat'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'HDS_NAME', 'HDS_NAME', 'hdsName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'CIVIC_ADDRESS_CLEAN', 'CIVIC_ADDRESS_CLEAN', 'civicAddressClean'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'BUS_NAME', 'BUS_NAME', 'busName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'FACILITY_DETAILS_ADDITIONAL_INFO', 'FACILITY_DETAILS_ADDITIONAL_INFO', 'facilityDetailsAdditionalInfo'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'HDS_TEL_AREA_CODE', 'HDS_TEL_AREA_CODE', 'hdsTelAreaCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'HDS_TEL_NUMBER', 'HDS_TEL_NUMBER', 'hdsTelNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'HDS_CELL_AREA_CODE', 'HDS_CELL_AREA_CODE', 'hdsCellAreaCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'HDS_CELL_NUMBER', 'HDS_CELL_NUMBER', 'hdsCellNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'HDS_FAX_AREA_CODE', 'HDS_FAX_AREA_CODE', 'hdsFaxAreaCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'HDS_FAX_NUMBER', 'HDS_FAX_NUMBER', 'hdsFaxNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'PHYS_PROCESS_STATUS', 'PHYS_PROCESS_STATUS', 'physProcessStatus'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'PHYS_MAILABILITY_SCORE', 'PHYS_MAILABILITY_SCORE', 'physMailabilityScore'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'PHYS_CITY', 'PHYS_CITY', 'physCity'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'PHYS_PROVINCE', 'PHYS_PROVINCE', 'physProvince'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'PHYS_PCODE', 'PHYS_PCODE', 'physPcode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'PHYS_COUNTRY', 'PHYS_COUNTRY', 'physCountry'
);


insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'PHYS_ADDR_1', 'PHYS_ADDR_1', 'physAddress1'
);


insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'PHYS_ADDR_2', 'PHYS_ADDR_2', 'physAddress2'
);


insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'PHYS_ADDR_3', 'PHYS_ADDR_3', 'physAddress3'
);


insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'PHYS_ADDR_4', 'PHYS_ADDR_4', 'physAddress4'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'BUILDING', 'BUILDING', 'building'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'UNIT', 'UNIT', 'unit'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'CIVIC_ADDRESS_CLEAN_OLD', 'CIVIC_ADDRESS_CLEAN_OLD', 'civicAddressCleanOld'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'MAIL_PROCESS_STATUS', 'MAIL_PROCESS_STATUS', 'mailProcessStatus'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'MAIL_MAILABILITY_SCORE', 'MAIL_MAILABILITY_SCORE', 'mailMailabilityScore'
);


insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'MAIL_CITY', 'MAIL_CITY', 'mailCity'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'MAIL_PROVINCE', 'MAIL_PROVINCE', 'mailProvince'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'MAIL_PCODE', 'MAIL_PCODE', 'mailPcode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'MAIL_COUNTRY', 'MAIL_COUNTRY', 'mailCountry'
);


insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'MAIL_ADDR_1', 'MAIL_ADDR_1', 'mailAddress1'
);


insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'MAIL_ADDR_2', 'MAIL_ADDR_2', 'mailAddress2'
);


insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'MAIL_ADDR_3', 'MAIL_ADDR_3', 'mailAddress3'
);


insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'MAIL_ADDR_4', 'MAIL_ADDR_4', 'mailAddress4'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_LATITUDE', 'DATABC_LATITUDE', 'databcLatitude'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_LONGITUDE', 'DATABC_LONGITUDE', 'databcLongitude'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_UNIT_NO', 'DATABC_UNIT_NO', 'databcUnitNo'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_CIVIC_NUMBER', 'DATABC_CIVIC_NUMBER', 'databcCivicNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_STREET_NAME', 'DATABC_STREET_NAME', 'databcStreetName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_STREET_TYPE', 'DATABC_STREET_TYPE', 'databcStreetType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_LOCALITY_NAME', 'DATABC_LOCALITY_NAME', 'databcLocalityName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_PROVINCE_CODE', 'DATABC_PROVINCE_CODE', 'databcProvinceCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_SITE_ID', 'DATABC_SITE_ID', 'databcSiteId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_SCORE', 'DATABC_SCORE', 'databcScore'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_MATCH_PRECISION', 'DATABC_MATCH_PRECISION', 'databcMatchPrecision'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_PRECISION_POINTS', 'DATABC_PRECISION_POINTS', 'databcPrecisionPoints'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_CHSA_CODE', 'DATABC_CHSA_CODE', 'databcChsaCode'
);


insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_CHSA_NAME', 'DATABC_CHSA_NAME', 'databcChsaName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_LHA_NAME', 'DATABC_LHA_NAME', 'databcLhaName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_HSDA_NAME', 'DATABC_HSDA_NAME', 'databcHsdaName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_HA_NAME', 'DATABC_HA_NAME', 'databcHaName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_USER_CHID', 'DATABC_USER_CHID', 'databcUserChid'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_PCN_CODE', 'DATABC_PCN_CODE', 'databcPcnCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_PCN_NAME', 'DATABC_PCN_NAME', 'databcPcnName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'TRUSTED_FILE', 'DATABC_STATUS', 'DATABC_STATUS', 'databcStatus'
);



