DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS status CASCADE;
DROP TABLE IF EXISTS control CASCADE;
DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS process_data;
DROP TABLE IF EXISTS source_data;
DROP TABLE IF EXISTS table_column_info;
DROP TABLE IF EXISTS table_columns_info;

CREATE TABLE IF NOT EXISTS table_column_info
(
    id bigint primary key generated by default as identity,	
	table_name VARCHAR(40) NOT NULL,
    column_name VARCHAR(40) NOT NULL,
	header_name VARCHAR(40), 
    variable_name VARCHAR(40) NULL,	
    UNIQUE(table_name, column_name)
);


CREATE TABLE IF NOT EXISTS users (
  id bigint primary key generated by default as identity,	
  user_id VARCHAR(30) UNIQUE NOT NULL,
  first_name VARCHAR(40),
  last_name VARCHAR(40),
  active_flag BOOLEAN DEFAULT TRUE,
  created_by varchar(30) DEFAULT CURRENT_USER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_by VARCHAR(30),	
  updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS roles (
  id bigint primary key generated by default as identity,	
  code VARCHAR(16) UNIQUE NOT NULL,
  description VARCHAR(40) NOT NULL
);


CREATE TABLE IF NOT EXISTS status (
  id bigint primary key generated by default as identity,	
  code VARCHAR(30) UNIQUE NOT NULL,
  description VARCHAR(130),
  is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS user_role (
  id bigint primary key generated by default as identity,		
  user_id VARCHAR(30)  references users(user_id) NOT NULL,
  role_code VARCHAR(16)  references roles(code) NOT NULL,
  UNIQUE(user_id, role_code)
);

CREATE TABLE IF NOT EXISTS control (
  id bigint primary key generated by default as identity,	
  file_name VARCHAR(80) UNIQUE NOT NULL,
  user_id VARCHAR(30) NOT NULL,
  file_extracted_date DATE,
  batch_label_name VARCHAR(30) NOT NULL,
  load_type_facility BOOLEAN DEFAULT FALSE,	
  load_type_hds BOOLEAN DEFAULT FALSE,
  load_type_bus_org BOOLEAN DEFAULT FALSE,
  load_type_o_f_relationship BOOLEAN DEFAULT FALSE,
  load_type_o_o_relationship BOOLEAN DEFAULT FALSE,
  load_type_i_o_relationship BOOLEAN DEFAULT FALSE,
  load_type_wl_org_xref BOOLEAN DEFAULT FALSE,
  load_type_wl_prac_ident_xref BOOLEAN DEFAULT FALSE,
  process_start_date TIMESTAMP(6) DEFAULT NOW(),
  process_end_date TIMESTAMP(6),
  status_code VARCHAR(30),
  created_by varchar(45) DEFAULT CURRENT_USER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_by VARCHAR(45),	
  updated_at TIMESTAMPTZ 
);

CREATE TABLE IF NOT EXISTS source_data (
  id bigint primary key generated by default as identity,
  control_id bigint NOT NULL,
  do_not_load VARCHAR(255), 
  internal_id VARCHAR(255),
  hds_surv_internal_id VARCHAR(255),
  facility_surv_internal_id VARCHAR(255),
  hds_source VARCHAR(255),
  hds_type_concat VARCHAR(255),
  hds_name VARCHAR(255),
  civic_address_clean VARCHAR(255),
  bus_name VARCHAR(255),
  facility_details_additional_info VARCHAR(255),
  hds_tel_area_code VARCHAR(255),
  hds_tel_number VARCHAR(255),
  hds_cell_area_code VARCHAR(255),
  hds_cell_number VARCHAR(255),
  hds_fax_area_code VARCHAR(255),
  hds_fax_number VARCHAR(255),
  phys_process_status VARCHAR(255),
  phys_mailability_score VARCHAR(255),
  phys_city VARCHAR(255),
  phys_province VARCHAR(255),
  phys_pcode VARCHAR(255),
  phys_country VARCHAR(255),
  phys_addr_1 VARCHAR(255),
  phys_addr_2 VARCHAR(255),
  phys_addr_3 VARCHAR(255),
  phys_addr_4 VARCHAR(255),
  building VARCHAR(255),
  unit VARCHAR(255),
  civic_address_clean_old VARCHAR(255),
  mail_process_status VARCHAR(255),
  mail_mailability_score VARCHAR(255),
  mail_city VARCHAR(255),
  mail_province VARCHAR(255),
  mail_pcode VARCHAR(255),
  mail_country VARCHAR(255),
  mail_addr_1 VARCHAR(255),
  mail_addr_2 VARCHAR(255),
  mail_addr_3 VARCHAR(255),
  mail_addr_4 VARCHAR(255),
  databc_latitude VARCHAR(255),
  databc_longitude VARCHAR(255),
  databc_unit_no VARCHAR(255),
  databc_civic_number VARCHAR(255),
  databc_street_name VARCHAR(255),
  databc_street_type VARCHAR(255),
  databc_locality_name VARCHAR(255),
  databc_province_code VARCHAR(255),
  databc_site_id VARCHAR(255),
  databc_score VARCHAR(255),
  databc_match_precision VARCHAR(255),
  databc_precision_points VARCHAR(255),
  databc_chsa_code VARCHAR(255),
  databc_chsa_name VARCHAR(255),
  databc_lha_name VARCHAR(255),
  databc_hsda_name VARCHAR(255),
  databc_ha_name VARCHAR(255),
  databc_user_chid VARCHAR(255),
  databc_pcn_code VARCHAR(255),
  databc_pcn_name VARCHAR(255),
  databc_status VARCHAR(255),
  created_by VARCHAR(30) DEFAULT CURRENT_USER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_by VARCHAR(30),	
  updated_at TIMESTAMPTZ,
     CONSTRAINT source_data_control_id_fk
      FOREIGN KEY(control_id) 
	  REFERENCES control(id)
);	

CREATE TABLE IF NOT EXISTS process_data (
  id bigint primary key NOT NULL,
  control_id bigint NOT NULL,
  do_not_load VARCHAR(255), 
  internal_id VARCHAR(255),
  hds_surv_internal_id VARCHAR(255),
  facility_surv_internal_id VARCHAR(255),
  hds_source VARCHAR(255),
  hds_type_concat VARCHAR(255),
  hds_name VARCHAR(255),
  civic_address_clean VARCHAR(255),
  bus_name VARCHAR(255),
  facility_details_additional_info VARCHAR(255),
  hds_tel_area_code VARCHAR(255),
  hds_tel_number VARCHAR(255),
  hds_cell_area_code VARCHAR(255),
  hds_cell_number VARCHAR(255),
  hds_fax_area_code VARCHAR(255),
  hds_fax_number VARCHAR(255),
  phys_process_status VARCHAR(255),
  phys_mailability_score VARCHAR(255),
  phys_city VARCHAR(255),
  phys_province VARCHAR(255),
  phys_pcode VARCHAR(255),
  phys_country VARCHAR(255),
  phys_addr_1 VARCHAR(255),
  phys_addr_2 VARCHAR(255),
  phys_addr_3 VARCHAR(255),
  phys_addr_4 VARCHAR(255),
  building VARCHAR(255),
  unit VARCHAR(255),
  civic_address_clean_old VARCHAR(255),
  mail_process_status VARCHAR(255),
  mail_mailability_score VARCHAR(255),
  mail_city VARCHAR(255),
  mail_province VARCHAR(255),
  mail_pcode VARCHAR(255),
  mail_country VARCHAR(255),
  mail_addr_1 VARCHAR(255),
  mail_addr_2 VARCHAR(255),
  mail_addr_3 VARCHAR(255),
  mail_addr_4 VARCHAR(255),
  databc_latitude VARCHAR(255),
  databc_longitude VARCHAR(255),
  databc_unit_no VARCHAR(255),
  databc_civic_number VARCHAR(255),
  databc_street_name VARCHAR(255),
  databc_street_type VARCHAR(255),
  databc_locality_name VARCHAR(255),
  databc_province_code VARCHAR(255),
  databc_site_id VARCHAR(255),
  databc_score VARCHAR(255),
  databc_match_precision VARCHAR(255),
  databc_precision_points VARCHAR(255),
  databc_chsa_code VARCHAR(255),
  databc_chsa_name VARCHAR(255),
  databc_lha_name VARCHAR(255),
  databc_hsda_name VARCHAR(255),
  databc_ha_name VARCHAR(255),
  databc_user_chid VARCHAR(255),
  databc_pcn_code VARCHAR(255),
  databc_pcn_name VARCHAR(255),
  databc_status VARCHAR(255),
  rowstatus_code VARCHAR(30),
  error_msg VARCHAR(500),
  created_by VARCHAR(30),
  created_at TIMESTAMPTZ,
  updated_by VARCHAR(30),	
  updated_at TIMESTAMPTZ,
     CONSTRAINT process_data_control_id_fk
      FOREIGN KEY(control_id) 
	  REFERENCES control(id),
     CONSTRAINT process_data_rowstatus_code_fk
      FOREIGN KEY(rowstatus_code) 
	  REFERENCES status(code)
);


