package com.moh.phlat.backend.model;

import java.util.List;
import java.util.Map;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class ProcessDataFilterParams{
	 private List<String> id;
	 private List<String> actions;
	 private List<String> rowstatusCode;
	 private List<String> doNotLoad;
	 private List<String> stakeholder;
	 private List<String> hdsIpcId;
	 private List<String> hdsCpnId;
	 private List<String> hdsProviderIdentifier1;
	 private List<String> hdsProviderIdentifier2;
	 private List<String> hdsProviderIdentifier3;
	 private List<String> hdsProviderIdentifierType1;
	 private List<String> hdsProviderIdentifierType2;
	 private List<String> hdsProviderIdentifierType3;
	 private List<String> hdsMspFacilityNumber;
	 private List<String> hdsHibcFacId;
	 private List<String> hdsType;
	 private List<String> hdsSubType;
	 private List<String> hdsName;
	 private List<String> hdsNameAlias;
	 private List<String> hdsPreferredNameFlag;
	 private List<String> hdsEmail;
	 private List<String> hdsWebsite;
	 private List<String> hdsBusTelAreaCode;
	 private List<String> hdsBusTelNumber;
	 private List<String> hdsTelExtension;
	 private List<String> hdsCellAreaCode;
	 private List<String> hdsCellNumber;
	 private List<String> hdsFaxAreaCode;
	 private List<String> hdsFaxNumber;
	 private List<String> pcnServiceDeliveryType;
	 private List<String> pcnClinicType;
	 private List<String> pcnPciFlag;
	 private List<String> hdsHoursOfOp;
	 private List<String> hdsContactName;
	 private List<String> hdsIsForProfitFlag;
	 private List<String> sourceStatus;
	 private List<String> pcnClinicStatus;
	 private List<String> hdsEffectiveStartDate;
	 private List<String> plrFacilityId;
	 private List<String> facRelnType;
	 private List<String> hdsParentIpcId;
	 private List<String> busIpcId;
	 private List<String> busCpnId;
	 private List<String> busName;
	 private List<String> busLegalName;
	 private List<String> busPayeeNum;
	 private List<String> busOwnerName;
	 private List<String> busOwnerType;
	 private List<String> busOwnerTypeOther;
	 private List<String> facAddressUnit;
	 private List<String> facBuildingName;
	 private List<String> facCivicAddr;
	 private List<String> facHdsDetailAddInfo;
	 private List<String> facLatitude;
	 private List<String> facLongitude;
	 private List<String> facSiteId;
	 private List<String> facScore;
	 private List<String> facMatchPrecision;
	 private List<String> facPrecisionPoints;
	 private List<String> facHsdaName;
	 private List<String> facChsaStatus;
	 private List<String> facPcnStatus;
	 private List<String> facChsaCode;
	 private List<String> facChsaName;
	 private List<String> facLhaName;
	 private List<String> facHaName;
	 private List<String> facPcnCode;
	 private List<String> facPcnName;
	 private List<String> physicalAddr1;
	 private List<String> physicalAddr2;
	 private List<String> physicalAddr3;
	 private List<String> physicalAddr4;
	 private List<String> physicalCity;
	 private List<String> physicalProvince;
	 private List<String> physicalPcode;
	 private List<String> physicalCountry;
	 private List<String> physicalAddrPrpsTypeCd;
	 private List<String> physicalAddrValidationStatus;
	 private List<String> physicalAddrMailabilityScore;
	 private List<String> physAddrIsPrivate;
	 private List<String> mailAddr1;
	 private List<String> mailAddr2;
	 private List<String> mailAddr3;
	 private List<String> mailAddr4;
	 private List<String> mailCity;
	 private List<String> mailProvince;
	 private List<String> mailPcode;
	 private List<String> mailCountry;
	 private List<String> mailAddrIsPriv;
	 private List<String> mailAddrPrpsTypeCd;
	 private List<String> mailAddrValidationStatus;
	 private List<String> mailAddrMailabilityScore;
	 private List<String> facIfcId;
	 private List<String> primaryCareGroupAction;
	 private List<String> primaryCareGroupEffectiveStartDate;
	 private List<String> primaryCareGroupEffectiveEndDate;
	 private List<String> hdsSubTypeGroupAction;
	 private List<String> hdsSubTypeGroupEffectiveStartDate;
	 private List<String> hdsSubTypeGroupEffectiveEndDate;
	 private List<String> hdsNameGroupAction;
	 private List<String> hdsNameGroupEffectiveStartDate;
	 private List<String> hdsNameGroupEffectiveEndDate;
	 private List<String> statusGroupAction;
	 private List<String> statusGroupEffectiveStartDate;
	 private List<String> statusGroupEffectiveEndDate;
	 private List<String> hdsEmailGroupAction;
	 private List<String> hdsEmailGroupEffectiveStartDate;
	 private List<String> hdsEmailGroupEffectiveEndDate;
	 private List<String> hdsWebsiteGroupAction;
	 private List<String> hdsWebsiteGroupEffectiveStartDate;
	 private List<String> hdsWebsiteGroupEffectiveEndDate;
	 private List<String> businessPhoneGroupAction;
	 private List<String> businessPhoneGroupEffectiveStartDate;
	 private List<String> businessPhoneGroupEffectiveEndDate;
	 private List<String> hdsFaxGroupAction;
	 private List<String> hdsFaxGroupEffectiveStartDate;
	 private List<String> hdsFaxGroupEffectiveEndDate;
	 private List<String> hdsCellGroupAction;
	 private List<String> hdsCellGroupEffectiveStartDate;
	 private List<String> hdsCellGroupEffectiveEndDate;
	 private List<String> physicalAddressGroupAction;
	 private List<String> physicalAddressGroupEffectiveStartDate;
	 private List<String> physicalAddressGroupEffectiveEndDate;	
	 private List<String> mailingAddressGroupAction;
	 private List<String> mailingAddressGroupEffectiveStartDate;
	 private List<String> mailingAddressGroupEffectiveEndDate;	 
	 private List<String> recordAction;

	 private Map<String,String> sort;
}