
CREATE TABLE IF NOT EXISTS table_column_info
(
    id bigint primary key generated by default as identity,
	table_name VARCHAR(40) NOT NULL,
    column_name VARCHAR(40) NOT NULL,
	header_name VARCHAR(40),
    variable_name VARCHAR(40) NULL,
    UNIQUE(table_name, column_name)
);

CREATE TABLE IF NOT EXISTS row_status (
  id bigint primary key generated by default as identity,
  code VARCHAR(30) UNIQUE NOT NULL,
  description VARCHAR(1000),
  is_deleted BOOLEAN DEFAULT FALSE
);


CREATE TABLE IF NOT EXISTS control (
  id bigint primary key generated by default as identity,
  file_name VARCHAR(80) UNIQUE NOT NULL,
  user_id VARCHAR(30) NOT NULL,
  file_extracted_date DATE,
  batch_label_name VARCHAR(30) NOT NULL,
  load_type_facility BOOLEAN DEFAULT FALSE,
  load_type_hds BOOLEAN DEFAULT FALSE,
  load_type_bus_org BOOLEAN DEFAULT FALSE,
  load_type_o_f_relationship BOOLEAN DEFAULT FALSE,
  load_type_o_o_relationship BOOLEAN DEFAULT FALSE,
  load_type_i_o_relationship BOOLEAN DEFAULT FALSE,
  load_type_wl_org_xref BOOLEAN DEFAULT FALSE,
  load_type_wl_prac_ident_xref BOOLEAN DEFAULT FALSE,
  process_start_date TIMESTAMP(6) DEFAULT NOW(),
  process_end_date TIMESTAMP(6),
  status_code VARCHAR(30),
  created_by varchar(45) DEFAULT CURRENT_USER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_by VARCHAR(45),
  updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS source_data (
  id bigint primary key generated by default as identity,
  control_id bigint NOT NULL,
  do_not_load_flag VARCHAR(10),
  stakeholder VARCHAR(20),
  stakeholder_id VARCHAR(19),
  hds_ipc_id VARCHAR(19),
  hds_cpn_id VARCHAR(19),
  hds_provider_identifier1 VARCHAR(50),
  hds_provider_identifier2 VARCHAR(50) ,
  hds_provider_identifier3 VARCHAR(50),
  hds_provider_identifier_type1  VARCHAR(50),
  hds_provider_identifier_type2  VARCHAR(50),
  hds_provider_identifier_type3  VARCHAR(50),
  hds_msp_facility_number VARCHAR(50),
  hds_type VARCHAR(400),
  hds_sub_type VARCHAR(50),
  hds_name VARCHAR(100),
  hds_preferred_name_flag VARCHAR(1),
  hds_email  VARCHAR(50),
  hds_website  VARCHAR(50),
  hds_bus_tel_area_code VARCHAR(15), 
  hds_bus_tel_number VARCHAR(30), 
  hds_tel_extension VARCHAR(15),
  hds_cell_area_code VARCHAR(15), 
  hds_cell_number VARCHAR(30),
  hds_fax_area_code VARCHAR(15), 
  hds_fax_number VARCHAR(30),
  pcn_service_delivery_type VARCHAR(255),
  pcn_clinic_type VARCHAR(255), 
  pcn_pci_flag VARCHAR(1), 
  source_status VARCHAR(50),
  pcn_clinic_status VARCHAR(255), 
  hds_effective_start_date VARCHAR(255),
  fac_address_unit VARCHAR(100),
  fac_building_name VARCHAR(100), 
  physical_addr1 VARCHAR(255),
  physical_addr2 VARCHAR(255),
  physical_addr3 VARCHAR(255),
  physical_addr4 VARCHAR(255),
  physical_city VARCHAR(255),
  physical_province VARCHAR(255),
  physical_pcode VARCHAR(255),
  physical_country VARCHAR(255), 
  physical_addr_prps_type_cd VARCHAR(255),    
  mail_addr1 VARCHAR(255),
  mail_addr2 VARCHAR(255),
  mail_addr3 VARCHAR(255),
  mail_addr4 VARCHAR(255),
  mail_city VARCHAR(255),
  mail_bc VARCHAR(255),
  mail_pcode VARCHAR(255),
  mail_country VARCHAR(255),
  created_by VARCHAR(30) DEFAULT CURRENT_USER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_by VARCHAR(30),
  updated_at TIMESTAMPTZ,
     CONSTRAINT source_data_control_id_fk
      FOREIGN KEY(control_id)
	  REFERENCES control(id)
);

CREATE TABLE IF NOT EXISTS process_data (
  id bigint primary key NOT NULL,
  control_id bigint NOT NULL,
  do_not_load_flag VARCHAR(10),
  stakeholder VARCHAR(20),
  stakeholder_id VARCHAR(19),
  hds_ipc_id VARCHAR(19),
  hds_cpn_id VARCHAR(19),
  hds_provider_identifier1 VARCHAR(50),
  hds_provider_identifier2 VARCHAR(50) ,
  hds_provider_identifier3 VARCHAR(50),
  hds_provider_identifier_type1  VARCHAR(50),
  hds_provider_identifier_type2  VARCHAR(50),
  hds_provider_identifier_type3  VARCHAR(50),
  hds_msp_facility_number VARCHAR(50),
  hds_pauth_id VARCHAR(30),
  hds_category_code VARCHAR(15), 
  hds_role_type_code VARCHAR(15), 
  hds_type VARCHAR(400),
  hds_sub_type VARCHAR(50),
  hds_user_chid VARCHAR(50),
  hds_created_dts VARCHAR(255),
  hds_invalidated_dts VARCHAR(255),
  hds_name VARCHAR(100),
  hds_preferred_name_flag VARCHAR(1),
  hds_email  VARCHAR(50),
  hds_website  VARCHAR(50),
  hds_bus_tel_area_code VARCHAR(15), 
  hds_bus_tel_number VARCHAR(30), 
  hds_tel_extension VARCHAR(15),
  hds_cell_area_code VARCHAR(15), 
  hds_cell_number VARCHAR(30),
  hds_fax_area_code VARCHAR(15), 
  hds_fax_number VARCHAR(30),
  pcn_service_delivery_type VARCHAR(255),
  pcn_clinic_type VARCHAR(255), 
  pcn_pci_flag VARCHAR(1), 
  hds_status VARCHAR(50) DEFAULT 'Active',
  source_status VARCHAR(50),
  pcn_clinic_status VARCHAR(255), 
  hds_effective_start_date VARCHAR(255),
  hds_effective_end_date VARCHAR(255) DEFAULT '9999-12-30',
  fac_address_unit VARCHAR(100),
  fac_building_name VARCHAR(100), 
  fac_civic_addr_id VARCHAR(30),
  fac_civic_addr VARCHAR(255),
  fac_latitude VARCHAR(255),
  fac_longitude VARCHAR(255),
  fac_street_direction VARCHAR(255),
  street_direction_prefix VARCHAR(255),
  street_type_prefix VARCHAR(255), 
  fac_civic_number VARCHAR(255),
  fac_street_name VARCHAR(255),
  fac_street_type VARCHAR(255),
  fac_locality_name VARCHAR(255),
  fac_province_code VARCHAR(255),
  fac_site_id VARCHAR(255),
  fac_score VARCHAR(255),
  fac_match_precision VARCHAR(255),
  fac_precision_points VARCHAR(255),
  fac_hsda_name VARCHAR(255),
  fac_databc_results VARCHAR(255),
  fac_pcn_code VARCHAR(255),
  fac_pcn_name VARCHAR(255),
  fac_chsa_status VARCHAR(255),
  fac_pcn_status VARCHAR(255),
  fac_chsa_code VARCHAR(255),
  fac_chsa_name VARCHAR(255),
  fac_lha_name VARCHAR(255),
  fac_ha_name VARCHAR(255),
  fac_reln_type VARCHAR(240),
  fac_type_code VARCHAR(255) DEFAULT 'BUILDING',
  physical_addr1 VARCHAR(255),
  physical_addr2 VARCHAR(255),
  physical_addr3 VARCHAR(255),
  physical_addr4 VARCHAR(255),
  physical_city VARCHAR(255),
  physical_province VARCHAR(255),
  physical_pcode VARCHAR(255),
  physical_country VARCHAR(255), 
  physical_addr_prps_type_cd VARCHAR(255),  
  physical_address_validation_status VARCHAR(19),  
  mail_addr1 VARCHAR(255),
  mail_addr2 VARCHAR(255),
  mail_addr3 VARCHAR(255),
  mail_addr4 VARCHAR(255),
  mail_city VARCHAR(255),
  mail_bc VARCHAR(255),
  mail_pcode VARCHAR(255),
  mail_country VARCHAR(255),
  mail_address_validation_status VARCHAR(19),
  plr_facility_id VARCHAR(30),
  rowstatus_code VARCHAR(30),
  created_by VARCHAR(30),
  created_at TIMESTAMPTZ,
  updated_by VARCHAR(30),
  updated_at TIMESTAMPTZ,
     CONSTRAINT process_data_control_id_fk
      FOREIGN KEY(control_id)
	  REFERENCES control(id),
     CONSTRAINT process_data_rowstatus_code_fk
      FOREIGN KEY(rowstatus_code)
	  REFERENCES row_status(code)
);

CREATE TABLE IF NOT EXISTS messages (
  id bigint primary key generated by default as identity,
  process_data_id bigint NOT NULL,
  message_code VARCHAR(25) NOT NULL,
  message_type VARCHAR(25) NOT NULL,
  message_desc  TEXT NOT NULL,
  source_system_name VARCHAR(25) NOT NULL,
  source_system_message_code VARCHAR(25),
  source_system_message_type VARCHAR(25),
  source_system_message_desc  TEXT,
  created_at TIMESTAMPTZ,
  created_by VARCHAR(30),

  CONSTRAINT message_detail_process_data_id_fk
      FOREIGN KEY(process_data_id)
	  REFERENCES process_data(id)
);


CREATE TABLE IF NOT EXISTS columns_display_preference (
  id bigint primary key generated by default as identity,
  user_id VARCHAR(30) NOT NULL,
  view_name VARCHAR(40) NOT NULL,
  display_columns TEXT[],
  created_at TIMESTAMPTZ,
  created_by VARCHAR(30),
  updated_by VARCHAR(30),
  updated_at TIMESTAMPTZ,
  CONSTRAINT user_pref_unique UNIQUE(user_id, view_name)
);


DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM   pg_constraint
        WHERE  conname = 'user_viewname_unique_constraint'
    ) THEN
        ALTER TABLE columns_display_preference
        ADD CONSTRAINT user_viewname_unique_constraint UNIQUE (user_id, view_name);
    END IF;
END$$;


