INSERT INTO row_status (code, description) VALUES
('INITIAL', 'The Source file upload has completed. The PHLAT Tool assigns a starting row status for each record in the PHLAT Process File.'),
('DO_NOT_LOAD', 'Indicates a user has excluded the record from loading into PLR. This status may be either set by the PHLAT Tool or PHLAT User.'),
('ON_HOLD', 'Implies deferred loading of the record into PLR. The record is not to be loaded at this time.'),
('VALID', 'Indicates the PHLAT Tool Source file validation has completed with no errors. The record is ready to be loaded into PLR. This is the only record ROWSTATUS value that allows loading into PLR.'),
('INVALID', 'Outcomes of record validations indicates one or more errors that require user correction.'),
('WARNING', 'Outcomes of record validations indicates one or more warnings that require user review to identify any invalid information. The record must be either updated and re-validated or the user may override the record status and manually change the status to either VALID, ON_HOLD, DO_NOT_LOAD, or POTENTIAL_DUPLICATE.'),
('POTENTIAL_DUPLICATE', 'Outcomes of record validations indicates potential duplicate record and requires user review to verify duplicate entity. If the record has 1 or more potential duplicate validation codes and no associated Error Codes, the ROWSTATUS is set to POTENTIAL_DUPLICATE. Records flagged as Potential Duplicate must have 2 or more potential duplicate records and may have one or more WARNING codes assigned to it. The user may override the record status and manually change the status to either VALID, ON_HOLD, DO_NOT_LOAD.'),
('COMPLETED', 'The System has completed the data load into PLR. This status can not be manually altered.'),
('LOAD_ERROR', 'Data load into PLR was not able to complete. The user may override the record status and manually change the status to either ON_HOLD, or DO_NOT_LOAD.');

-- seeded data for table and column info
-- this table stores the column header name used for uploading and the variable names used for UI Hide and Show feature
insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'ID', '', 'id'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'DO_NOT_LOAD_FLAG', 'DO_NOT_LOAD_FLAG', 'doNotLoadFlag'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'STAKEHOLDER', 'STAKEHOLDER', 'stakeholder'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'STAKEHOLDER_ID', 'STAKEHOLDER_ID', 'stakeholderId'
);


insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_IPC_ID', 'HDS_IPC_ID', 'hdsIpcId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_CPN_ID', 'HDS_CPN_ID', 'hdsCpnId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_PROVIDER_IDENTIFIER1', 'HDS_PROVIDER_IDENTIFIER1', 'hdsProviderIdentifier1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_PROVIDER_IDENTIFIER2', 'HDS_PROVIDER_IDENTIFIER2', 'hdsProviderIdentifier2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_PROVIDER_IDENTIFIER3', 'HDS_PROVIDER_IDENTIFIER3', 'hdsProviderIdentifier3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_PROVIDER_IDENTIFIER_TYPE1', 'HDS_PROVIDER_IDENTIFIER_TYPE1', 'hdsProviderIdentifierType1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_PROVIDER_IDENTIFIER_TYPE2', 'HDS_PROVIDER_IDENTIFIER_TYPE2', 'hdsProviderIdentifierType2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_PROVIDER_IDENTIFIER_TYPE3', 'HDS_PROVIDER_IDENTIFIER_TYPE3', 'hdsProviderIdentifierType3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_MSP_FACILITY_NUMBER', 'HDS_MSP_FACILITY_NUMBER', 'hdsMspFacilityNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_TYPE', 'HDS_TYPE', 'hdsType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_SUB_TYPE', 'HDS_SUB_TYPE', 'hdsSubType'
);


insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_NAME', 'HDS_NAME', 'hdsName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_PREFERRED_NAME_FLAG', 'HDS_PREFERRED_NAME_FLAG', 'hdsPreferredNameFlag'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_EMAIL', 'HDS_EMAIL', 'hdsEmail'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_WEBSITE', 'HDS_WEBSITE', 'hdsWebsite'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_BUS_TEL_AREA_CODE', 'HDS_BUS_TEL_AREA_CODE', 'hdsBusTelAreaCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_BUS_TEL_NUMBER', 'HDS_BUS_TEL_NUMBER', 'hdsBusTelNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_TEL_EXTENSION', 'HDS_TEL_EXTENSION', 'hdsTelExtension'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_CELL_AREA_CODE', 'HDS_CELL_AREA_CODE', 'hdsCellAreaCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_CELL_NUMBER', 'HDS_CELL_NUMBER', 'hdsCellNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_FAX_AREA_CODE', 'HDS_FAX_AREA_CODE', 'hdsFaxAreaCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_FAX_NUMBER', 'HDS_FAX_NUMBER', 'hdsFaxNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PCN_SERVICE_DELIVERY_TYPE', 'PCN_SERVICE_DELIVERY_TYPE', 'pcnServiceDeliveryType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PCN_CLINIC_TYPE', 'PCN_CLINIC_TYPE', 'pcnClinicType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PCN_PCI_FLAG', 'PCN_PCI_FLAG', 'pcnPciFlag'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'SOURCE_STATUS', 'SOURCE_STATUS', 'sourceStatus'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PCN_CLINIC_STATUS', 'PCN_CLINIC_STATUS', 'pcnClinicStatus'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'HDS_EFFECTIVE_START_DATE', 'HDS_EFFECTIVE_START_DATE', 'hdsEffectiveStartDate'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'FAC_ADDRESS_UNIT', 'FAC_ADDRESS_UNIT', 'facAddressUnit'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'FAC_BUILDING_NAME', 'FAC_BUILDING_NAME', 'facBuildingName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_ADDR1', 'PHYSICAL_ADDR1', 'physicalAddr1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_ADDR2', 'PHYSICAL_ADDR2', 'physicalAddr2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_ADDR3', 'PHYSICAL_ADDR3', 'physicalAddr3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_ADDR4', 'PHYSICAL_ADDR4', 'physicalAddr4'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_CITY', 'PHYSICAL_CITY', 'physicalCity'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_PROVINCE', 'PHYSICAL_PROVINCE', 'physicalProvince'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_PCODE', 'PHYSICAL_PCODE', 'physicalPcode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_COUNTRY', 'PHYSICAL_COUNTRY', 'physicalCountry'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'PHYSICAL_ADDR_PRPS_TYPE_CD', 'PHYSICAL_ADDR_PRPS_TYPE_CD', 'physicalAddrPrpsTypeCd'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_ADDR1', 'MAIL_ADDR1', 'mailAddr1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_ADDR2', 'MAIL_ADDR2', 'mailAddr2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_ADDR3', 'MAIL_ADDR3', 'mailAddr3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_ADDR4', 'MAIL_ADDR4', 'mailAddr4'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_CITY', 'MAIL_CITY', 'mailCity'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_BC', 'MAIL_BC', 'mailBc'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_PCODE', 'MAIL_PCODE', 'mailPcode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'SOURCE_DATA', 'MAIL_COUNTRY', 'MAIL_COUNTRY', 'mailCountry'
);

-- process data table
insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'ID', 'ID', 'id'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'CONTROL_ID', 'CONTROL_ID', 'controlTableId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'STAKEHOLDER', 'STAKEHOLDER', 'stakeholder'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_IPC_ID', 'HDS_IPC_ID', 'hdsIpcId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_CPN_ID', 'HDS_CPN_ID', 'hdsCpnId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER1', 'HDS_PROVIDER_IDENTIFIER1', 'hdsProviderIdentifier1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER2', 'HDS_PROVIDER_IDENTIFIER2', 'hdsProviderIdentifier2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER3', 'HDS_PROVIDER_IDENTIFIER3', 'hdsProviderIdentifier3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER_TYPE1', 'HDS_PROVIDER_IDENTIFIER_TYPE1', 'hdsProviderIdentifierType1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER_TYPE2', 'HDS_PROVIDER_IDENTIFIER_TYPE2', 'hdsProviderIdentifierType2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER_TYPE3', 'HDS_PROVIDER_IDENTIFIER_TYPE3', 'hdsProviderIdentifierType3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_MSP_FACILITY_NUMBER', 'HDS_MSP_FACILITY_NUMBER', 'hdsMspFacilityNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_TYPE', 'HDS_TYPE', 'hdsType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_SUB_TYPE', 'HDS_SUB_TYPE', 'hdsSubType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_NAME', 'HDS_NAME', 'hdsName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PREFERRED_NAME_FLAG', 'HDS_PREFERRED_NAME_FLAG', 'hdsPreferredNameFlag'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_EMAIL', 'HDS_EMAIL', 'hdsEmail'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_WEBSITE', 'HDS_WEBSITE', 'hdsWebsite'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_BUS_TEL_AREA_CODE', 'HDS_BUS_TEL_AREA_CODE', 'hdsBusTelAreaCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_BUS_TEL_NUMBER', 'HDS_BUS_TEL_NUMBER', 'hdsBusTelNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_TEL_EXTENSION', 'HDS_TEL_EXTENSION', 'hdsTelExtension'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_CELL_AREA_CODE', 'HDS_CELL_AREA_CODE', 'hdsCellAreaCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_CELL_NUMBER', 'HDS_CELL_NUMBER', 'hdsCellNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_FAX_AREA_CODE', 'HDS_FAX_AREA_CODE', 'hdsFaxAreaCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_FAX_NUMBER', 'HDS_FAX_NUMBER', 'hdsFaxNumber'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PCN_SERVICE_DELIVERY_TYPE', 'PCN_SERVICE_DELIVERY_TYPE', 'pcnServiceDeliveryType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PCN_CLINIC_TYPE', 'PCN_CLINIC_TYPE', 'pcnClinicType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PCN_PCI_FLAG', 'PCN_PCI_FLAG', 'pcnPciFlag'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_STATUS', 'HDS_STATUS', 'hdsStatus'
);
insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'SOURCE_STATUS', 'SOURCE_STATUS', 'sourceStatus'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PCN_CLINIC_STATUS', 'PCN_CLINIC_STATUS', 'pcnClinicStatus'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_EFFECTIVE_START_DATE', 'HDS_EFFECTIVE_START_DATE', 'hdsEffectiveStartDate'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PLR_FACILITY_ID', 'PLR_FACILITY_ID', 'plrFacilityId'
);


insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_RELN_TYPE', 'FAC_RELN_TYPE', 'facRelnType'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_ADDRESS_UNIT', 'FAC_ADDRESS_UNIT', 'facAddressUnit'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_BUILDING_NAME', 'FAC_BUILDING_NAME', 'facBuildingName '
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_CIVIC_ADDR', 'FAC_CIVIC_ADDR', 'facCivicAddr'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_LATITUDE', 'FAC_LATITUDE', 'facLatitude'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_LONGITUDE', 'FAC_LONGITUDE', 'facLongitude'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_SITE_ID', 'FAC_SITE_ID', 'facSiteId'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_SCORE', 'FAC_SCORE', 'facScore'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_MATCH_PRECISION', 'FAC_MATCH_PRECISION', 'facMatchPrecision'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_PRECISION_POINTS', 'FAC_PRECISION_POINTS', 'facPprecisionPoints'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_HSDA_NAME', 'FAC_HSDA_NAME', 'facHsdaName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_CHSA_STATUS', 'FAC_CHSA_STATUS', 'facChsaStatus '
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_PCN_STATUS', 'FAC_PCN_STATUS', 'facPcnStatus '
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_CHSA_CODE', 'FAC_CHSA_CODE', 'facChsaCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_CHSA_NAME', 'FAC_CHSA_NAME', 'facChsaName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_LHA_NAME', 'FAC_LHA_NAME', 'facLhaName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_HA_NAME', 'FAC_HA_NAME', 'facHaName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_PCN_CODE', 'FAC_PCN_CODE', 'facPcnCode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_PCN_NAME', 'FAC_PCN_NAME', 'facPcnName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_ADDR1', 'PHYSICAL_ADDR1', 'physicalAddr1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_ADDR2', 'PHYSICAL_ADDR2', 'physicalAddr2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_ADDR3', 'PHYSICAL_ADDR3', 'physicalAddr3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_ADDR4', 'PHYSICAL_ADDR4', 'physicalAddr4'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_CITY', 'PHYSICAL_CITY', 'physicalCity'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_PROVINCE', 'PHYSICAL_PROVINCE', 'physicalProvince'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_PCODE', 'PHYSICAL_PCODE', 'physicalPcode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_COUNTRY', 'PHYSICAL_COUNTRY', 'physicalCountry'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_ADDR_PRPS_TYPE_CD', 'PHYSICAL_ADDR_PRPS_TYPE_CD', 'physicalAddrPrpsTypeCd'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_ADDRESS_VALIDATION_STATUS', 'PHYSICAL_ADDRESS_VALIDATION_STATUS', 'physicalAddressValidationStatus'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_ADDR1', 'MAIL_ADDR1', 'mailAddr1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_ADDR2', 'MAIL_ADDR2', 'mailAddr2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_ADDR3', 'MAIL_ADDR3', 'mailAddr3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_ADDR4', 'MAIL_ADDR4', 'mailAddr4'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_CITY', 'MAIL_CITY', 'mailCity'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_BC', 'MAIL_BC', 'mailBc'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_PCODE', 'MAIL_PCODE', 'mailPcode'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_COUNTRY', 'MAIL_COUNTRY', 'mailCountry'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_ADDR_PRPS_TYPE_CD', 'MAIL_ADDR_PRPS_TYPE_CD', 'mailAddrPrpsTypeCd'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_ADDRESS_VALIDATION_STATUS', 'MAIL_ADDRESS_VALIDATION_STATUS', 'mailAddressValidationStatus'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'ROWSTATUS_CODE', 'ROWSTATUS_CODE', 'rowstatusCode'
);

