delete from TABLE_COLUMN_INFO where TABLE_NAME = 'PROCESS_DATA';

-- process data table
insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME, UI_COLUMN_HEADER) VALUES (
'PROCESS_DATA', 'ID', 'ID', 'Rcd ID'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'CONTROL_ID', 'CONTROL_ID', 'File ID'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'STAKEHOLDER', 'STAKEHOLDER', 'Stakeholder'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_CPN_ID', 'HDS_CPN_ID', 'HDS IPC'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_IPC_ID', 'HDS_IPC_ID', 'HDS CPN'
);


insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER1', 'HDS_PROVIDER_IDENTIFIER1', 'HDS Provider ID 1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER2', 'HDS_PROVIDER_IDENTIFIER2', 'HDS Provider ID 2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER3', 'HDS_PROVIDER_IDENTIFIER3', 'HDS Provider ID 3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER_TYPE1', 'HDS_PROVIDER_IDENTIFIER_TYPE1', 'HDS Provider ID Type 1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER_TYPE2', 'HDS_PROVIDER_IDENTIFIER_TYPE2', 'HDS Provider ID Type 2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PROVIDER_IDENTIFIER_TYPE3', 'HDS_PROVIDER_IDENTIFIER_TYPE3', 'HDS Provider ID Type 3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_MSP_FACILITY_NUMBER', 'HDS_MSP_FACILITY_NUMBER', 'HDS MSP Facility #'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_TYPE', 'HDS_TYPE', 'HDS Type'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_SUB_TYPE', 'HDS_SUB_TYPE', 'HDS Sub Type'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_NAME', 'HDS_NAME', 'HDS Name'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_PREFERRED_NAME_FLAG', 'HDS_PREFERRED_NAME_FLAG', 'HDS Pref Name Flag'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_EMAIL', 'HDS_EMAIL', 'HDS Email'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_WEBSITE', 'HDS_WEBSITE', 'HDS Web Site'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_BUS_TEL_AREA_CODE', 'HDS_BUS_TEL_AREA_CODE', 'HDS Tel Area CD'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_BUS_TEL_NUMBER', 'HDS_BUS_TEL_NUMBER', 'HDS Tel #'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_TEL_EXTENSION', 'HDS_TEL_EXTENSION', 'HDS Tel Ext.'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_CELL_AREA_CODE', 'HDS_CELL_AREA_CODE', 'HDS Cell # Area CD'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_CELL_NUMBER', 'HDS_CELL_NUMBER', 'HDS Cell #'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_FAX_AREA_CODE', 'HDS_FAX_AREA_CODE', 'HDS Fax Area CD'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_FAX_NUMBER', 'HDS_FAX_NUMBER', 'HDS FAX #'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PCN_SERVICE_DELIVERY_TYPE', 'PCN_SERVICE_DELIVERY_TYPE', 'PCN Service Delivery Type'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PCN_CLINIC_TYPE', 'PCN_CLINIC_TYPE', 'PCN Clinic Type'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PCN_PCI_FLAG', 'PCN_PCI_FLAG', 'PCN PCI Flag'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'SOURCE_STATUS', 'SOURCE_STATUS', 'Source Status'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PCN_CLINIC_STATUS', 'PCN_CLINIC_STATUS', 'PCN Clinic Status'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'HDS_EFFECTIVE_START_DATE', 'HDS_EFFECTIVE_START_DATE', 'HDS Operation Start Date'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PLR_FACILITY_ID', 'PLR_FACILITY_ID', 'PLR Facility ID'
);


insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_RELN_TYPE', 'FAC_RELN_TYPE', 'Facility Relationship Type'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_ADDRESS_UNIT', 'FAC_ADDRESS_UNIT', 'Facility Addr Unit #'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_BUILDING_NAME', 'FAC_BUILDING_NAME', 'Facility Building Name'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_CIVIC_ADDR', 'FAC_CIVIC_ADDR', 'Facility Civic Addr'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_LATITUDE', 'FAC_LATITUDE', 'Facility Civic Addr Latitude'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_LONGITUDE', 'FAC_LONGITUDE', 'Facility Civic Addr Longitude'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_SITE_ID', 'FAC_SITE_ID', 'Facility Civic Addr Site'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_SCORE', 'FAC_SCORE', 'Facity Civic Addr Score'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_MATCH_PRECISION', 'FAC_MATCH_PRECISION', 'Facility Civic Addr Match Precision'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_PRECISION_POINTS', 'FAC_PRECISION_POINTS', 'Facility Civic Addr Precision Points'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_HSDA_NAME', 'FAC_HSDA_NAME', 'Facility HSDA Name'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_CHSA_STATUS', 'FAC_CHSA_STATUS', 'Facility CHSA Status'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_PCN_STATUS', 'FAC_PCN_STATUS', 'Facility PCN Status'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_CHSA_CODE', 'FAC_CHSA_CODE', 'Facility CHSA CD'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_CHSA_NAME', 'FAC_CHSA_NAME', 'facChsaName'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_LHA_NAME', 'FAC_LHA_NAME', 'Facily LHA Name'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_HA_NAME', 'FAC_HA_NAME', 'Facility HA Name'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_PCN_CODE', 'FAC_PCN_CODE', 'Facility PCN Code'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'FAC_PCN_NAME', 'FAC_PCN_NAME', 'Facility PCN Name'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_ADDR1', 'PHYSICAL_ADDR1', 'Physical Addr 1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_ADDR2', 'PHYSICAL_ADDR2', 'Physical Addr 2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_ADDR3', 'PHYSICAL_ADDR3', 'Physical Addr 3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_ADDR4', 'PHYSICAL_ADDR4', 'physical Addr 4'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_CITY', 'PHYSICAL_CITY', 'Physical Addr City'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_PROVINCE', 'PHYSICAL_PROVINCE', 'Physical Addr Prov'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_PCODE', 'PHYSICAL_PCODE', 'Physical Postal'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_COUNTRY', 'PHYSICAL_COUNTRY', 'Physical Cntry'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'PHYSICAL_ADDRESS_VALIDATION_STATUS', 'PHYSICAL_ADDRESS_VALIDATION_STATUS', 'Physical Addr Val Status'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_ADDR1', 'MAIL_ADDR1', 'Mailing Addr 1'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_ADDR2', 'MAIL_ADDR2', 'Mailing Addr 2'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_ADDR3', 'MAIL_ADDR3', 'Mailing Addr 3'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_ADDR4', 'MAIL_ADDR4', 'Mailing Addr 4'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_CITY', 'MAIL_CITY', 'Mailing City'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_BC', 'MAIL_BC', 'Mailing Prov'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_PCODE', 'MAIL_PCODE', 'Mailing Postal'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_COUNTRY', 'MAIL_COUNTRY', 'Mailing Cntry'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'MAIL_ADDRESS_VALIDATION_STATUS', 'MAIL_ADDRESS_VALIDATION_STATUS', 'Mailing Val Status'
);

insert into TABLE_COLUMN_INFO(TABLE_NAME, COLUMN_NAME, HEADER_NAME, VARIABLE_NAME) VALUES (
'PROCESS_DATA', 'ROWSTATUS_CODE', 'ROWSTATUS_CODE', 'Rcd Status'
);

