name: ZAP Scan
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to ZAP Scan'
        type: environment
        required: true
      api-token:
        description: 'JWT Token for ZAP API scan'
        required: true
        
concurrency: ${{ github.event.inputs.environment }}

env:
  ZAP_AUTH_HEADER: 'Bearer'
  ZAP_AUTH_HEADER_VALUE: ${{ inputs.api-token }}

jobs:
  zap_scan:
    name: Run ZAP Scan
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: ${{ vars.APPLICATION_URL }}
          artifact_name: zap_fe_scan
      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          target: ${{ vars.VITE_BACKEND_API_URL }}v3/api-docs
          artifact_name: zap_api_scan
