name: ZAP Scan
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to ZAP Scan'
        type: environment
        required: true
      run_fe_scan:
        description: 'Execute the scan for the frontend'
        type: boolean
        required: true
      run_api_scan:
        description: 'Execute the scan for the API'
        type: boolean
        required: true
      api-token:
        description: 'JWT Token for ZAP API scan'
        required: true
        
concurrency: ${{ github.event.inputs.environment }}

env:
  ZAP_AUTH_HEADER: 'Authorization'
  ZAP_AUTH_HEADER_VALUE: ${{ inputs.api-token }}

jobs:
  zap_scan_fe:
    name: Run Frontend ZAP Scan
    if: inputs.run_fe_scan == true
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: ZAP Frontend Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: ${{ vars.APPLICATION_URL }}
          artifact_name: zap_fe_scan
  zap_scan_api:
    name: Run API ZAP Scan
    if: inputs.run_api_scan == true
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.9.0
        with:
          target: ${{ vars.VITE_BACKEND_API_URL }}v3/api-docs
          artifact_name: zap_api_scan